import { afterEach, describe, expect, it } from "vitest";
import { createApp } from "./app.js";
import { MemoryConnectionStore } from "./connection-store.js";
import { UnconfiguredAskProvider, type AskProvider } from "./ask-provider.js";
import { MemoryViewStore } from "./view-store.js";

afterEach(() => { delete process.env.ORBIT_API_TOKEN; });
describe("gateway Explore vertical slice", () => {
  it("lists demo connections and native objects", async () => { const app = createApp(); const connections = await (await app.request("/api/connections")).json(); expect(connections.data[0].demo).toBe(true); const objects = await (await app.request("/api/connections/demo_postgres/objects")).json(); expect(objects.data.objects[0]).toMatchObject({ namespace: "public", name: "users", kind: "table" }); });
  it("validates limits and returns request IDs", async () => { const response = await createApp().request("/api/explore", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ connectionId: "demo_postgres", namespace: "public", object: "users", limit: 1000 }) }); expect(response.status).toBe(400); expect(response.headers.get("X-Request-ID")).toBeTruthy(); });
  it("paginates through an adapter cursor", async () => { const response = await createApp().request("/api/explore", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ connectionId: "demo_postgres", namespace: "public", object: "users", limit: 2 }) }); const payload = await response.json(); expect(payload.data.rows).toHaveLength(2); expect(payload.data.nextCursor).toBeTypeOf("string"); });
  it("resolves linked records through the gateway transport", async () => { const response = await createApp().request("/api/references/resolve", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ connectionId: "demo_postgres", database: "public", sourceCollection: "subscriptions", field: "user_id", value: "usr_8f2a19", reference: { namespace: "public", object: "users", column: "id" } }) }); const payload = await response.json(); expect(response.status).toBe(200); expect(payload.data).toMatchObject({ strategy: "foreign_key", matches: [{ collection: "users", document: { email: "maya@northstar.de" } }] }); });
  it("enforces bearer authentication when configured", async () => { process.env.ORBIT_API_TOKEN = "test-token"; expect((await createApp().request("/api/connections")).status).toBe(401); expect((await createApp().request("/api/connections", { headers: { Authorization: "Bearer test-token" } })).status).toBe(200); });
  it("rejects invalid connection creation without storing it", async () => { const store = new MemoryConnectionStore(); const response = await createApp(store).request("/api/connections", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Missing fields" }) }); expect(response.status).toBe(400); expect(await store.list()).toHaveLength(0); });
  it("protects the built-in demo from mutation", async () => { const app = createApp(); expect((await app.request("/api/connections/demo_postgres", { method: "DELETE" })).status).toBe(400); expect((await app.request("/api/connections/demo_postgres", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Changed" }) })).status).toBe(400); });
});

describe("gateway Ask vertical slice", () => {
  const provider: AskProvider = {
    async generateQuery(_input, report) { await report?.({ type: "activity", activityId: "query-generation", stage: "generating", status: "started", message: "Requesting a query plan", model: "test/model" }); await report?.({ type: "output", activityId: "query-generation", stage: "generating", delta: '{"query":"SELECT id' }); await report?.({ type: "activity", activityId: "query-generation", stage: "generating", status: "completed", message: "Query plan received", model: "test/model" }); return { query: "SELECT id, email, plan FROM public.users LIMIT 25", assumptions: ["Active demo records are representative."], sourceObjects: ["public.users"], visualization: { kind: "table", x: null, y: [] } }; },
    async summarize() { return "The evidence contains five users across the available plans."; },
  };
  it("generates an inspectable draft without executing it", async () => { const response = await createApp(new MemoryConnectionStore(), true, provider).request("/api/ask/draft", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ connectionIds: ["demo_postgres"], question: "Show users by plan", context: { namespace: "public", object: "users" } }) }); const payload = await response.json(); expect(response.status).toBe(200); expect(payload.data).toMatchObject({ queryLanguage: "sql", query: expect.stringContaining("SELECT"), sourceObjects: [{ name: "users" }] }); expect(payload.data).not.toHaveProperty("evidence"); });
  it("streams real preparation milestones and provider output before returning the draft", async () => { const response = await createApp(new MemoryConnectionStore(), true, provider).request("/api/ask/stream", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ connectionIds: ["demo_postgres"], question: "Show users by plan", context: { namespace: "public", object: "users" } }) }); const body = await response.text(); expect(response.status).toBe(200); expect(response.headers.get("content-type")).toContain("text/event-stream"); for (const stage of ["discovering", "inspecting", "generating", "validating"]) expect(body).toContain(`\"stage\":\"${stage}\"`); expect(body).toContain('"type":"activity"'); expect(body).toContain('"type":"output"'); expect(body).toContain("test/model"); expect(body).toContain('"type":"draft"'); expect(body).toContain("SELECT id, email, plan"); });
  it("executes a reviewed read-only query with evidence and an evidence-backed answer", async () => { const source = { connectionId: "demo_postgres", namespace: "public", name: "users", kind: "table" }; const response = await createApp(new MemoryConnectionStore(), true, provider).request("/api/ask/execute", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ connectionId: "demo_postgres", question: "Show users by plan", query: "SELECT id, email, plan FROM public.users LIMIT 25", queryLanguage: "sql", assumptions: [], sourceObjects: [source], visualization: { kind: "table" } }) }); const payload = await response.json(); expect(response.status).toBe(200); expect(payload.data.answer).toContain("five users"); expect(payload.data.evidence.rows).toHaveLength(5); expect(payload.data.query).toContain("SELECT"); });
  it("rejects a destructive edited query before the adapter", async () => { const source = { connectionId: "demo_postgres", namespace: "public", name: "users", kind: "table" }; const response = await createApp(new MemoryConnectionStore(), true, provider).request("/api/ask/execute", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ connectionId: "demo_postgres", question: "Remove users", query: "DELETE FROM users", queryLanguage: "sql", assumptions: [], sourceObjects: [source] }) }); expect(response.status).toBe(400); expect((await response.json()).code).toBe("QUERY_REJECTED"); });
});

describe("gateway Views vertical slice", () => {
  const viewInput = { name: "Users table", connectionId: "demo_postgres", component: "table", source: { kind: "explore", namespace: "public", object: "users", filters: [], sort: [] }, visualization: { kind: "table" } };
  it("creates, refreshes, duplicates, and removes a view", async () => { const store = new MemoryViewStore(); const app = createApp(new MemoryConnectionStore(), true, new UnconfiguredAskProvider(), store); const createdResponse = await app.request("/api/views", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(viewInput) }); const created = (await createdResponse.json()).data; expect(createdResponse.status).toBe(201); const refreshed = await (await app.request(`/api/views/${created.id}/refresh`, { method: "POST" })).json(); expect(refreshed.data.result.rows).toHaveLength(5); expect(refreshed.data.view.status).toBe("fresh"); expect((await app.request(`/api/views/${created.id}/duplicate`, { method: "POST" })).status).toBe(201); expect((await app.request(`/api/views/${created.id}`, { method: "DELETE" })).status).toBe(200); });
  it("serves shared results through a revocable opaque token", async () => { const store = new MemoryViewStore(); const app = createApp(new MemoryConnectionStore(), true, new UnconfiguredAskProvider(), store); const created = (await (await app.request("/api/views", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(viewInput) })).json()).data; const share = (await (await app.request(`/api/views/${created.id}/share`, { method: "POST" })).json()).data; const publicResponse = await app.request(`/shared/views/${share.token}`); expect(publicResponse.status).toBe(200); expect((await publicResponse.json()).data.view).not.toHaveProperty("source"); await app.request(`/api/views/${created.id}/share`, { method: "DELETE" }); expect((await app.request(`/shared/views/${share.token}`)).status).toBe(404); });
});
